on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
     branches: [main]
  
jobs:
  build:
    strategy:
      matrix:
        combo:
          - ubuntu-latest
    runs-on: "${{ matrix.combo }}"
    steps:
      - run: sleep 120
