name: nix flake update
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update
    - uses: peter-evans/create-pull-request@v4
      with:
        title: "chore: nix flake update"
        commit-message: "chore: nix flake update"
        branch: "chore/nix-flake-update"